# https://taskfile.dev

version: "3"

vars:
  REPOSITORY: ghcr.io/adrianliechti/wingman-extractor

tasks:
  run:
    cmds:
      - docker run -it --rm --pull always -p 8000:8000 {{.REPOSITORY}}

  publish:
    cmds:
      - docker buildx build . --push --platform linux/amd64,linux/arm64 --tag {{.REPOSITORY}}:latest
    
  generate:
    cmds:
      - ./.venv/bin/python -m grpc_tools.protoc -I. --python_out=. --pyi_out=. --grpc_python_out=. extractor.proto